
name: CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:


jobs:
  website_update:
    runs-on: ubuntu-latest
    steps:

      - name: Git clone my repo
        uses: actions/checkout@v2

      - name: Current folder
        run: pwd
        
      - name: List folder
        run: ls -la
        
      - name: Update website
        uses: nogsantos/scp-deploy@master
        with:
          src: ./html/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
